1. FROM (어떤 테이블?)
- ANIMAL_OUTS

2. WHERE (걸러야 하는 조건?)
- HOUR(DATETIME)이 9 이상 19 이하인 것만

3. GROUP BY (무엇 기준으로 묶나?)
- HOUR(DATETIME) 기준

4. SELECT / ORDER BY (무엇을 보여주고 정렬하나?)
- SELECT: HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
- ORDER BY: HOUR ASC

SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT 
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR ASC;