# 2️⃣ [1. FROM / JOIN]
- FROM FIRST_HALF F JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR

# 3️⃣ [2. WHERE / HAVING]
- 없음

# 4️⃣ [3. GROUP BY]
- GROUP BY INGREDIENT_TYPE

# 1️⃣ [4. SELECT / ORDER BY]
- SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
- ORDER BY TOTAL_ORDER ASC